version: '3'

services:

  demo-db:
    image: containterregistrynamepopruxandramaria30643.azurecr.io/db:latest
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root"]
      timeout: 45s
      interval: 10s
      retries: 5
    restart: always
    container_name: db
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=popruxi
      - POSTGRES_PASSWORD=ruxi
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"

  demo-be:
    image: containterregistrynamepopruxandramaria30643.azurecr.io/popruxandramaria30643backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_IP=db
      - DB_PORT=5432
      - DB_USER=popruxi
      - DB_PASSWORD=ruxi
      - DB_NAME=db
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - demo-db

